'''4. Comprueba el funcionamiento del ejercicio con los siguientes valores 
reales (Vibrio Cholerae). Cuidado con los posibles “saltos de línea” al copiar
la cadena que aparece abajo.'''

# INICIALIZACION
genoma = "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC"
kmer= "TGATCA"
contador = 0

# OPERACIONES

for i in range(len(genoma)):
    print("Fragmiento de genoma: {}".format(genoma[i:i+7]))
    if genoma[i:i+7].find(kmer) !=-1 :
        contador +=1

# SALIDA
print ("La secuencia kmer aparece {} veces".format(contador))
